// Phase 4.5 T1-01 — inline the Anchor IDL as a TypeScript const so the
// published @alea-drand/sdk has ZERO Node filesystem dependencies at runtime.
// Any browser bundler (Vite, webpack, Next.js App Router, esbuild) can
// then import the SDK without fs/url/path polyfills.
//
// Regenerate when the IDL at src/idl/alea_verifier.json changes.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const idlPath = join(__dirname, "..", "src", "idl", "alea_verifier.json");
const outPath = join(__dirname, "..", "src", "idl.ts");

const idl = JSON.parse(readFileSync(idlPath, "utf-8"));
const pretty = JSON.stringify(idl, null, 2);

const banner = `// AUTO-GENERATED by scripts/generate-idl-ts.mjs — DO NOT EDIT.
// Source of truth: src/idl/alea_verifier.json (committed, derived from
// programs/alea-verifier's Anchor IDL). Regenerate with:
//   npm run generate-idl
//
// This file exists so @alea-drand/sdk can be imported in any browser bundler
// without Node fs/path deps. Phase 4.5 T1-01 fix.
`;

const content = `${banner}
import type { Idl } from "@coral-xyz/anchor";

// The IDL as a typed const. Consumers who need the raw object can
// import this re-export; the client code uses it internally.
export const IDL = ${pretty} as Idl;
`;

writeFileSync(outPath, content);
console.log(`Wrote ${outPath} (${content.length} bytes, from ${idlPath})`);
